# Generated by Django 3.2.5 on 2021-08-03 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(default=100, unique=True)),
                ('first_name', models.CharField(default=' ', max_length=120)),
                ('last_name', models.CharField(default=' ', max_length=120)),
                ('mobile_no', models.IntegerField(default=0)),
                ('address', models.TextField(default=' ', max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=1, unique=True)),
                ('product_name', models.CharField(default=' ', max_length=150)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(default=' ', max_length=600)),
                ('image', models.CharField(default=' ', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='orders_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=1, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.customers')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
        ),
    ]
